var messageList = [
  "Greetings",
  "Time Travel",
  "Future Is Bright",
  "Code Developer",
  "Fly High",
  "Flying Colors",
  "Soar High",
  "Soaring Heights",
  "Empower Yourself",
  "Falling Leaves",
  "The Fall Season",
  "Jump for Joy",
  "Cliffhanger",
  "Mountain Explorer",
  "Rend the Skies",
  "Red Roses",
  "Blue Sky",
  "Green Fields",
  "Yellow Sunshine",
  "Golden Moments",
  "Demon Slayer",
  "Demonic Forces",
  "Panda Adventures",
  "Cat Whisperer",
  "Kitty Love",
  "Kitten Cuteness",
  "Zero Gravity",
  "Memory Lane",
  "Trooper Spirit",
  "XX Marks the Spot",
  "Bandit's Lair",
  "Fearless Warrior",
  "Light Bringer",
  "Glowing Ember",
  "Tread Carefully",
  "Deep Dive",
  "Deeper Understanding",
  "Deepest Thoughts",
  "Mine Your Mind",
  "Your Journey",
  "Worst Nightmare",
  "Enemy Within",
  "Hostile Territory",
  "Force of Nature",
  "Video Game Pro",
  "Donkey Kong Fan",
  "Mule Rider",
  "Colt Companion",
  "Cult Leader",
  "Cultist Secrets",
  "Magnum Opus",
  "Gun Enthusiast",
  "Assault Tactics",
  "Recon Expert",
  "Trap Master",
  "Trapper's Delight",
  "Redeem Your Destiny",
  "Code Master",
  "Script Writer",
  "Near and Far",
  "Close Encounters",
  "Open Sesame",
  "Cube Explorer",
  "Circle of Life",
  "Geo Adventurer",
  "Genome Explorer",
  "Germ Buster",
  "Spaz Attack",
  "Shot Caller",
  "Echo Effect",
  "Beta Tester",
  "Alpha Achiever",
  "Gamma Ray",
  "Omega Supreme",
  "Seal the Deal",
  "Squid Squad",
  "Money Maker",
  "Cash Flow",
  "Lord of the Rings",
  "King of Hearts",
  "Duke of Destiny",
  "Rest and Relax",
  "Fire Starter",
  "Flame Warrior",
  "Morrow's Promise",
  "Break Free",
  "Breaker of Chains",
  "Numb to Feelings",
  "Ice Breaker",
  "Cold As Ice",
  "Rotten Luck",
  "Sick Beats",
  "Sickly Sweet",
  "Janitorial Duties",
  "Camel Rider",
  "Rooster Crows",
  "Sand Dunes",
  "Desert Mirage",
  "Dessert Lover",
  "Hurdle Jumper",
  "Racer's Edge",
  "Eraser of Mistakes",
  "Erase the Past",
  "Big Dreams",
  "Small Beginnings",
  "Short Circuit",
  "Tall Tales",
  "Sith Lord",
  "Bounty Hunter",
  "Cracked Code",
  "Broken Chains",
  "Sad Symphony",
  "Happy Endings",
  "Joyful Moments",
  "Crimson Sky",
  "Destiny Awaits",
  "Deceitful Paths",
  "Lies Unraveled",
  "Seek the Truth",
  "Destined for Greatness",
  "Bloxxer Champion",
  "Hawk's Vision",
  "Eagle Eye",
  "Hawker of Goods",
  "Walker's Journey",
  "Zombie Slayer",
  "Sarge in Charge",
  "Captain Courage",
  "Punching Numbers",
  "One and Only",
  "Two for Tea",
  "Uno Dos Tres",
  "Slice of Life",
  "Slash and Burn",
  "Melting Moments",
  "Melted Dreams",
  "Melting Pot",
  "Fell From Grace",
  "Wolf Pack",
  "Hound's Howl",
  "Legacy Builder",
  "Sharp Wit",
  "Dead End",
  "Mew the Cat",
  "Chuckle Master",
  "Bubba Gump",
  "Bubble Burst",
  "Sandwich Lover",
  "Smasher of Records",
  "Extreme Explorer",
  "Multi-dimensional",
  "Universe Unraveled",
  "Ultimate Victory",
  "Death Defier",
  "Ready for Anything",
  "Monkey Business",
  "Elevator Pitch",
  "Wrench Turner",
  "Grease Monkey",
  "Head Honcho",
  "Theme Park Enthusiast",
  "Grand Vision",
  "Cool Breeze",
  "Kid at Heart",
  "Boy Wonder",
  "Girl Power",
  "Vortex Explorer",
  "Paradox Unveiled",
];
export default function getRandomMessage() {
  return messageList[Math.floor(Math.random() * messageList.length)];
}
